included:
  - Sources

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Tests
  - Support
  - docs
  - build

disabled_rules: # rule identifiers to exclude from running
  - fallthrough
  - large_tuple
  - todo

line_length: 
  - 200 #warning
  - 250 #error

type_body_length:
  - 700 #warning
  - 1000 #error

file_length:
  - 1000 #warning
  - 1200 #error

function_body_length:
  - 125 #warning
  - 200 #error

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 50

identifier_name:
  excluded:
    - id
    - i
    - j
    - k

  explicit_failure_calls:
    name: "Avoid asserting 'false'"
    regex: '((assert|precondition)\(false)'
    message: "Use assertionFailure() or preconditionFailure() instead."
    severity: warning  

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
